public enum UpgradeType
{
    Health,
    HealthRegen,
    AttackDamage,
    AbilityPower,
    Armor,
    MagicResistance,
    MoveSpeed,
    CriticalChance,
    CriticalDamage,
    ArmorPenetration,
    MagicPenetration,
    LifeSteal,
    Omnivamp,
    Haste,
    HealingPower,
    PickUpRange,
    ExpMultiplier
}